default:
    - override hydra/output: local
    - override hydra/launcher: local

algo: redq

# Logger
exp_name: ${task}_sac_${visual_transform}
visual_transform:
record_interval: 100  # every 100 data collection we evaluate
num_record_envs: 1
device: "cuda:0"
device_collection: ["cuda:1","cuda:1"]
wandb_entity: "RLHive"
wandb_mode: "offline"
wandb_project: "REDQ_TorchRL"

# Environment
task: franka_slide_close-v3
frame_skip: 1
reward_scaling: 5.0
init_env_steps: 1000
seed: 42
eval_traj: 25

# Collector
env_per_collector: 4
max_frames_per_traj: -1
total_frames: 10_000_000
init_random_frames: 2_500
frames_per_batch: 400

# Replay Buffer
prb: 1
buffer_size: 1000000
buffer_scratch_dir: /tmp/

# Optimization
gamma: 0.99
batch_size: 256
lr: 3.0e-4
weight_decay: 0.0
target_update_polyak: 0.995
utd_ratio: 10
clip_norm: 1.0

hydra:
    job:
        name: sac_${task}_${seed}
