default:
- override hydra/output: local
- override hydra/launcher: local
env: FK1_MicroOpenRandom_v2d-v4
algorithm: NPG
seed: 3
sample_mode: trajectories
rl_num_traj: 200
rl_num_samples: 0
num_cpu: 10
rl_num_iter: 500
save_freq: 100
eval_rollouts: 100
exp_notes: 'J4:v0.5baselines. J3:V0.4wrap Baseline J2: Pose(pos+euler) in obs and
  proprio, A new way to get dof_proximity. J1: Kitchen-v4 baselines post env refactors,
  J0: V0.4 Baseline. RandomDesk is now the entry point'
policy_size: (64, 64)
init_log_std: -0.1
min_log_std: -1.0
vf_hidden_size: (128, 128)
vf_batch_size: 64
vf_epochs: 2
vf_learn_rate: 0.001
rl_step_size: 0.05
rl_gamma: 0.995
rl_gae: 0.97
alg_hyper_params:
  device: cpu
job_name: v0.6baselines
suite_name: kitchen
wandb_params:
  use_wandb: true
  wandb_user: jayluvsgeography
  wandb_project: v0.6_baselines_kitchen
  wandb_exp: v0.6_FK1_MicroOpenRandom_v2d-v4_3
