seed: 1
device: 'cuda'
encoder: r3m18
cam_name: right_cam
from_pixels: True
env_name: FK1_Knob1OnRandom_v2d-v4
data_file: /home/rutavms/data/robohive/FK1-v4/FK1_Knob1OnRandom_v2d-v4/seed1/best_policy20230402-003930_trace.h5

bc_epochs: 500
bc_batch_size: 128
bc_lr: 1e-4
policy_size: [256, 256]
init_log_std: -1.0
min_log_std: -3.0

eval_traj: 25
wandb_entity: "rutavms"
wandb_mode: "offline"
wandb_project: "SAC_TorchRL"

hydra:
    run:
        dir: temp
    job:
        chdir: True
