default:
    - override hydra/output: local
    - override hydra/launcher: local

# general inputs
env               :   kitchen-v4              # placeholder name
algorithm         :   NPG
seed              :   123
sample_mode       :   trajectories
rl_num_traj       :   200
rl_num_samples    :   0                       # will be ignored when sample_mode=trajectories
num_cpu           :   10
rl_num_iter       :   1001
save_freq         :   100
eval_rollouts     :   100
# exp_notes         :  "J0:Adding franka_appliance class. Adding random envs. Refactor multi_task_base_v1. J2: Training DEMO_ENTRY_POINT. J3: Bugfix for horizon. J4: Sensor configs. J5: making a train to commit the baselines 5b: random_entry_point. J6> Testing new microwave position. J7: Random entry point redo post v0.2 update (serialization fix, env seed)+Franka_micro_open H 75. J5d: ENTRY_POINT = RANDOM_ENTRY_POINT. 1a0ddda (HEAD -> v0.1dev, tag: v0.1, origin/v0.1dev, origin/v0.1). J8:Baselines for v0.2 J8c: Debugging kitchen_ldoor_close-v3. Running more seeds for V0.1"
exp_notes         :  'J4:v0.5baselines. J3:V0.4wrap Baseline J2: Pose(pos+euler) in obs and proprio, A new way to get dof_proximity. J1: Kitchen-v4 baselines post env refactors, J0: V0.4 Baseline. RandomDesk is now the entry point'

# RL parameters (all params related to PG, value function etc.)
policy_size       :   (64, 64)
init_log_std      :   -0.1
min_log_std       :   -1.0
vf_hidden_size    :   (128, 128)
vf_batch_size     :   64
vf_epochs         :   2
vf_learn_rate     :   1e-3
rl_step_size      :   0.05
rl_gamma          :   0.995
rl_gae            :   0.97

# Algorithm hyperparameters : if alg requires additional params, can be specified here (or defaults will be used)

alg_hyper_params  :   {'device': 'cpu'}

# general outputs
job_name          : v0.5baselines
suite_name        : kitchen

wandb_params:
    use_wandb     : True
    wandb_user    : vikashplus
    wandb_project : v0.5_baselines
    wandb_exp     : v0.5_${env}

hydra:
    job:
        name: ${env}
